### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by alexterente** [feuvan/opencore-amr-iOS#1]
Hi Feuvan,

I am using your opencore-amr-iOS to try to decode a sound on an ios device.
I have manage to build and import the library in to the iOS project with no problem.
I inclue the #include "interf_dec.h" in to my .m file and I initialize a decoder void *amr = Decoder_Interface_init();, but when i try to use Decoder_Interface_Decode I get an error from Xcode saying that "No matching function for call to "Decoder_Interface_Decode"" even if I do a cmd+click on the method it will take me to its definition it the interf_dec.h.
Have you experienced such thing? Can you help me to use the Decoder_Interface_Decode? 
Any advice, link, book is well come.
Thanks for all your work to create the opencore-amr-iOS git project.

Best regards,
Alex Terente

**Comment by feuvan** [comment]
can't reproduce
