### ISSUE TITLE
build_ios_xcode6.sh can not build xcode 10.1

### ISSUE THREAD

**Issue by AsteriskZuo** [feuvan/opencore-amr-iOS#6]
This is config.log

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by opencore-amr configure 0.1.3, which was
generated by GNU Autoconf 2.68.  Invocation command line was

  $ ./configure --prefix=/Users/yu.zuo/codes/opencore-amr-iOS/opencore-amr-iOS --disable-shared

## --------- ##

hostname = yuzuos-iMac.local
uname -m = x86_64
uname -r = 18.2.0
uname -s = Darwin
uname -v = Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
Kernel configured for up to 8 processors.
4 processors are physically available.
8 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 16.00 gigabytes
Default processor set: 371 tasks, 1693 threads, 8 processors
Load average: 2.12, Mach factor: 5.86
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /Applications/Wireshark.app/Contents/MacOS

## ----------- ##

configure:2576: checking for a BSD-compatible install
configure:2644: result: /usr/bin/install -c
configure:2655: checking whether build environment is sane
configure:2705: result: yes
configure:2846: checking for a thread-safe mkdir -p
configure:2885: result: ./install-sh -c -d
configure:2898: checking for gawk
configure:2914: found /usr/local/bin/gawk
configure:2925: result: gawk
configure:2936: checking whether make sets $(MAKE)
configure:2958: result: yes
configure:3033: checking how to create a ustar tar archive
configure:3046: tar --version
bsdtar 2.8.3 - libarchive 2.8.3
configure:3049: $? = 0
configure:3089: tardir=conftest.dir && eval tar --format=ustar -chf - "$tardir" >conftest.tar
configure:3092: $? = 0
configure:3096: tar -xf - <conftest.tar
configure:3099: $? = 0
configure:3112: result: gnutar
configure:3130: checking whether make supports nested variables
configure:3147: result: yes
configure:3161: checking whether to enable maintainer-specific portions of Makefiles
configure:3170: result: no
configure:3189: checking build system type
configure:3203: result: x86_64-apple-darwin18.2.0
configure:3223: checking host system type
configure:3236: result: x86_64-apple-darwin18.2.0
configure:3449: checking for C++ compiler version
configure:3458: xcrun --sdk iphonesimulator clang++ -arch i386  -miphoneos-version-min=6.0 --version >&5
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: i386-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:3469: $? = 0
configure:3458: xcrun --sdk iphonesimulator clang++ -arch i386  -miphoneos-version-min=6.0 -v >&5
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: i386-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: warning: argument unused during compilation: '-miphoneos-version-min=6.0' [-Wunused-command-line-argument]
configure:3469: $? = 0
configure:3458: xcrun --sdk iphonesimulator clang++ -arch i386  -miphoneos-version-min=6.0 -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3469: $? = 1
configure:3458: xcrun --sdk iphonesimulator clang++ -arch i386  -miphoneos-version-min=6.0 -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:3469: $? = 1
configure:3489: checking whether the C++ compiler works
configure:3511: xcrun --sdk iphonesimulator clang++ -arch i386  -miphoneos-version-min=6.0    conftest.cpp  >&5
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7 [-Wdeprecated]
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
1 warning generated.
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3515: $? = 1
configure:3553: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "opencore-amr"
| #define PACKAGE_TARNAME "opencore-amr"
| #define PACKAGE_VERSION "0.1.3"
| #define PACKAGE_STRING "opencore-amr 0.1.3"
| #define PACKAGE_BUGREPORT "http://sourceforge.net/projects/opencore-amr/"
| #define PACKAGE_URL ""
| #define PACKAGE "opencore-amr"
| #define VERSION "0.1.3"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3558: error: in `/Users/yu.zuo/codes/opencore-amr-iOS':
configure:3560: error: C++ compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_build=x86_64-apple-darwin18.2.0
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value='xcrun --sdk iphonesimulator clang++ -arch i386  -miphoneos-version-min=6.0'
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-apple-darwin18.2.0
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AWK=gawk
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes
am_cv_prog_tar_ustar=gnutar

## ----------------- ##

ACLOCAL='${SHELL} /Users/yu.zuo/codes/opencore-amr-iOS/missing --run aclocal-1.11'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMRNB_DECODER_FALSE='#'
AMRNB_DECODER_TRUE=''
AMRNB_ENCODER_FALSE='#'
AMRNB_ENCODER_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
AR=''
AUTOCONF='${SHELL} /Users/yu.zuo/codes/opencore-amr-iOS/missing --run autoconf'
AUTOHEADER='${SHELL} /Users/yu.zuo/codes/opencore-amr-iOS/missing --run autoheader'
AUTOMAKE='${SHELL} /Users/yu.zuo/codes/opencore-amr-iOS/missing --run automake-1.11'
AWK='gawk'
CC=''
CCDEPMODE=''
CFLAGS=''
COMPILE_AS_C_FALSE='#'
COMPILE_AS_C_TRUE=''
CPP=''
CPPFLAGS=''
CXX='xcrun --sdk iphonesimulator clang++ -arch i386  -miphoneos-version-min=6.0'
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
EXAMPLES_FALSE=''
EXAMPLES_TRUE='#'
EXEEXT=''
FGREP=''
GCC_ARMV5_FALSE=''
GCC_ARMV5_TRUE='#'
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIBTOOL_DEPS=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /Users/yu.zuo/codes/opencore-amr-iOS/missing --run makeinfo'
MANIFEST_TOOL=''
MKDIR_P='./install-sh -c -d'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OPENCORE_AMRNB_VERSION=''
OPENCORE_AMRWB_VERSION=''
OTOOL64=''
OTOOL=''
PACKAGE='opencore-amr'
PACKAGE_BUGREPORT='http://sourceforge.net/projects/opencore-amr/'
PACKAGE_NAME='opencore-amr'
PACKAGE_STRING='opencore-amr 0.1.3'
PACKAGE_TARNAME='opencore-amr'
PACKAGE_URL=''
PACKAGE_VERSION='0.1.3'
PATH_SEPARATOR=':'
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
VERSION='0.1.3'
ac_ct_AR=''
ac_ct_CC=''
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='tar --format=ustar -chf - "$$tardir"'
am__untar='tar -xf -'
bindir='${exec_prefix}/bin'
build='x86_64-apple-darwin18.2.0'
build_alias=''
build_cpu='x86_64'
build_os='darwin18.2.0'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-apple-darwin18.2.0'
host_alias=''
host_cpu='x86_64'
host_os='darwin18.2.0'
host_vendor='apple'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /Users/yu.zuo/codes/opencore-amr-iOS/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(top_builddir)/./install-sh -c -d'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/Users/yu.zuo/codes/opencore-amr-iOS/opencore-amr-iOS'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "opencore-amr"
#define PACKAGE_TARNAME "opencore-amr"
#define PACKAGE_VERSION "0.1.3"
#define PACKAGE_STRING "opencore-amr 0.1.3"
#define PACKAGE_BUGREPORT "http://sourceforge.net/projects/opencore-amr/"
#define PACKAGE_URL ""
#define PACKAGE "opencore-amr"
#define VERSION "0.1.3"

configure: exit 77

**Comment by AsteriskZuo** [comment]
我尝试了多次，也没有找到原因，请指教。

**Comment by AsteriskZuo** [comment]
我将 -miphoneos-version-min=9.0 设置高了之后，少了错误，但是提示
configure:3659: error: in `/Users/yu.zuo/codes/opencore-amr-iOS':
configure:3661: error: cannot run C++ compiled programs.

**Comment by AsteriskZuo** [comment]
主要是没有生成conftest.cpp文件

**Comment by AsteriskZuo** [comment]
或者楼主是否可以生成一个xcode工程文件给我。谢谢。

**Comment by feuvan** [comment]
resolved in 52fdd31e00c75ac5b07af09e7d9fd19e2210ec1c
